export const GET_USER_SUCCESS = "GET_USERINFO_SUCCESS";
export const GET_USER_FAIL = "GET_USERINFO_FAIL";
export const GET_USER_ALLINFO = "GET_USER_ALLINFO";
export const GET_USER_PLAN = "GET_USER_PLAN";
